@IsTest
private class ContractPDFtest {
  @IsTest
  static void testEmptyConstructor() {
    ContractPDFcontroller controller = new ContractPDFcontroller();
  }

  @IsTest static void testParameter() {
    // ApexPages.currentPage().getParameters().put('id', 'TODO');
    ContractPDFcontroller controller = new ContractPDFcontroller();
  }

  @IsTest static void testId() {

  }

  @IsTest static void testRecord() {

  }

  @IsTest static void testStandard() {

  }
}
